# https://docs.gitlab.cn/jh/ci/quick_start/

before_script:
    - echo $CI_COMMIT_REF_NAME
    - whoami
    - npm config set registry https://registry.npmmirror.com/
    - pnpm install --reporter=silent

stages:
    - prettier
    - eslint
    - stylelint
    - check-types
    - test
    - build

# 创建 MR 时执行；master 分支有 push 时执行
prettier:
    stage: prettier
    script:
        - pnpm prettier;
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME =~ /master/

# 创建 MR 时执行；master 分支有 push 时执行
eslint:
    stage: eslint
    script:
        - pnpm eslint;
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME =~ /master/

# 创建 MR 时执行；master 分支有 push 时执行
stylelint:
    stage: stylelint
    script:
        - pnpm stylelint;
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME =~ /master/

# 创建 MR 时执行；master 分支有 push 时执行
check-types:
    stage: check-types
    needs: [prettier, eslint, stylelint]
    script:
        - pnpm check-types;
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME =~ /master/

# 创建 MR 时执行；master 分支有 push 时执行
test:
    stage: test
    needs: [check-types]
    script:
        - pnpm test;
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME =~ /master/

# 创建 MR 时执行；master 分支有 push 时执行
build:
    stage: build
    needs: [test]
    script:
        - pnpm build;
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME =~ /master/
