name: CI

on:
    push:
        branches: 'master'
    pull_request:
        branches: '*'

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 14

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 6.35.1

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Run Prettier
              run: pnpm prettier

            - name: Run Eslint
              run: pnpm eslint

            - name: Run Stylelint
              run: pnpm stylelint

            - name: Run test
              run: pnpm test

            - name: Run check-types
              run: pnpm check-types

            - name: Run build
              run: pnpm build
