name: CI

on:
  push:
    branches: "*"
  pull_request:
    branches: ['master']

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.32.20

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Prettier
        run: pnpm prettier

      - name: Run Eslint
        run: pnpm eslint

      - name: Run Stylelint
        run: pnpm stylelint

      - name: Run test
        run: pnpm test

      - name: Run build
        run: pnpm build

      - name: Run web build
        run: |
          cd web
          pnpm install --frozen-lockfile
          pnpm build
